package com.bebo.bluefolio.domain;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@Entity
public class Stock {

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO) // defines that the
	// id is automatically generated by the database. Key generation is left
	// to the JPA provider to select (AUTO).
	private long id;
	private String symbol;
	private int price, quantity, totalprice;
	// private String brand, model, color, registerNumber;
	//private int year, price;
	
	public Stock() {}
	
	public Stock(String symbol, int price, int quantity) {
		super();
		this.symbol = symbol;
		this.price= price;
		this.quantity = quantity;
		this.totalprice = price*quantity;
	}
	
	
	public Stock(String symbol, int price, int quantity, Portfolio portfolio) {
		super();
		this.symbol = symbol;
		this.price= price;
		this.quantity = quantity;
		this.totalprice = price*quantity;
		this.portfolio = portfolio;
	}
	
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getSymbol() {
		return symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	public int getPrice() {
		return price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public int getQuantity() {
		return quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public int getTotalprice() {
		return totalprice;
	}

	public void setTotalprice(int totalprice) {
		this.totalprice = totalprice;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "portfolio")

	private Portfolio portfolio;
	
	// Getter and setter
	public Portfolio getPortfolio() {
		return portfolio;
	}
	
	public void setPortfolio(Portfolio portfolio) {
		this.portfolio = portfolio;
	}
	
}


